'use client';
import {useEffect,useState} from 'react';
import BrandAccessFields from '../../../components/brand-access-fields';
import ScopeFields from '../../../components/scope-fields';
export default function Consent(){const[data,setData]=useState<any>(null),[selected,setSelected]=useState<string[]>([]),[allBrands,setAllBrands]=useState(false),[scopes,setScopes]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/oauth/details',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:location.search.slice(1)})}).then(async r=>{if(r.status===401){location.assign('/?returnTo='+encodeURIComponent(location.pathname+location.search));return;}const d=await r.json();if(!r.ok)throw new Error(d.error_description||'Nie udało się odczytać autoryzacji.');setData(d);setScopes(d.scopes);}).catch(e=>setError(e.message));},[]);
 async function decide(deny=false){setBusy(true);setError('');try{const r=await fetch('/oauth/approve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:location.search.slice(1),brand_ids:allBrands?[]:selected,all_brands:allBrands,scopes,deny})});const d=await r.json();if(!r.ok)throw new Error(d.error_description||'Nie udało się zapisać zgody.');location.assign(d.redirect);}catch(e){setError((e as Error).message);setBusy(false);}}
 return <main className="auth-wrap"><section className="auth-card consent-card"><div className="logo-mark">M</div><h2 style={{marginTop:24}}>Połącz z MCPLinker</h2>{data?<><p>Aplikacja <strong>{data.client_name}</strong> prosi o dostęp. Nazwę podaje klient. Wybierz uprawnienia i marki.</p><div className="callout">Zezwalaj tylko na połączenie, które przed chwilą samodzielnie rozpocząłeś w ChatGPT lub Claude. Jeśli ktoś przysłał Ci ten link, kliknij Odmów.</div><p className="hint">Klient prosi o: {data.scopes.join(', ')}. Możesz przyznać więcej lub mniej, np. publikowanie.</p><ScopeFields selected={scopes} onChange={setScopes} disabled={busy}/><BrandAccessFields brands={data.brands} allBrands={allBrands} selected={selected} onAllChange={setAllBrands} onSelectedChange={setSelected} disabled={busy}/><p className="hint">Przekierowanie po autoryzacji:</p><code className="block-code">{data.redirect_uri}</code><button className="primary full" disabled={busy||!scopes.length||(!allBrands&&!selected.length)} onClick={()=>void decide()}>{busy?'Łączenie…':'Zezwól na dostęp'}</button><button className="text-button full" disabled={busy} onClick={()=>void decide(true)}>Odmów</button></>:<p>Sprawdzanie żądania…</p>}{error&&<div role="alert" className="error">{error}</div>}</section></main>;
}
