import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {execute} from '../lib/actions.mjs';
import {context} from '../lib/auth.mjs';
import {hash} from '../lib/security.mjs';
process.env.SUPABASE_URL='https://database.example.com';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';process.env.APP_URL='https://app.example.com';
const owner=randomUUID(),brand=randomUUID(),other=randomUUID(),connection=randomUUID();
const ctx={ownerId:owner,actor:'panel',scopes:['read','draft','publish','admin','manage'],brandIds:null};
const tables={brands:[{id:brand,owner_id:owner,publish_policy:'approval'},{id:other,owner_id:owner,publish_policy:'approval'}],connections:[{id:connection,owner_id:owner,brand_id:brand,platform:'facebook'}],posts:[],audit_log:[],api_keys:[],oauth_grants:[]};
function matches(row,params){for(const[k,v]of params){if(v.startsWith('eq.')&&String(row[k])!==v.slice(3))return false;if(v==='is.null'&&row[k]!=null)return false;if(v.startsWith('gt.')&&!(row[k]>v.slice(3)))return false;if(v.startsWith('in.')&&!v.slice(4,-1).split(',').includes(row[k]))return false;}return true;}
globalThis.fetch=async(url,options={})=>{const u=new URL(url),table=u.pathname.split('/').pop();if(!tables[table])throw new Error('Unexpected external request: '+u.origin);const args=options.body?JSON.parse(options.body):null;let result=tables[table].filter(r=>matches(r,u.searchParams));if(options.method==='POST'){const row={id:randomUUID(),status:'draft',attempts:0,approved_at:null,updated_at:new Date().toISOString(),...args};tables[table].push(row);result=[row];}if(options.method==='PATCH')for(const row of result)Object.assign(row,args);return new Response(JSON.stringify(result),{status:200});};
const input=()=>({brand_id:brand,connection_id:connection,title:'Example',content:'Body',payload:{},dedupe_key:randomUUID()});
test('draft creation is idempotent but does not accept changed content under same key',async()=>{const a=input();const one=await execute('post_create',a,ctx);const two=await execute('post_create',a,ctx);assert.equal(one.id,two.id);await assert.rejects(()=>execute('post_create',{...a,content:'Changed'},ctx),e=>e.status===409);});
test('approval policy prevents immediate platform calls',async()=>{const p=await execute('post_create',input(),ctx);const result=await execute('post_publish',{id:p.id},ctx);assert.equal(result.status,'approval');assert.equal(result.attempts,0);});
test('editing invalidates approval and scheduling data',async()=>{const p=await execute('post_create',input(),ctx);await execute('post_approve',{id:p.id,expected_updated_at:p.updated_at},ctx);assert.ok(tables.posts.find(x=>x.id===p.id).approved_at);const result=await execute('post_update',{id:p.id,expected_updated_at:tables.posts.find(x=>x.id===p.id).updated_at,title:'New',content:'Edited',payload:{}},ctx);assert.equal(result.approved_at,null);assert.equal(result.status,'draft');assert.equal(result.scheduled_at,null);});
test('approved posts can schedule, scheduled content cannot be edited',async()=>{const p=await execute('post_create',input(),ctx);await execute('post_approve',{id:p.id,expected_updated_at:p.updated_at},ctx);const r=await execute('post_schedule',{id:p.id,scheduled_at:new Date(Date.now()+3600000).toISOString()},ctx);assert.equal(r.status,'scheduled');await assert.rejects(()=>execute('post_update',{id:p.id,expected_updated_at:r.updated_at,title:'Edit',content:'Changed',payload:{}},ctx),e=>e.status===409);await execute('post_cancel',{id:p.id},ctx);assert.equal(tables.posts.find(x=>x.id===p.id).status,'cancelled');});
test('cross-brand targets and restricted agents are rejected',async()=>{await assert.rejects(()=>execute('post_create',{...input(),brand_id:other},ctx),e=>e.status===403);await assert.rejects(()=>execute('post_create',input(),{...ctx,actor:'agent',brandIds:[other]}),e=>e.status===403);});
test('uncertain posts cannot be published without panel reconciliation',async()=>{const p=await execute('post_create',input(),ctx);tables.posts.find(x=>x.id===p.id).status='uncertain';await assert.rejects(()=>execute('post_publish',{id:p.id},ctx),e=>e.status===409);await execute('post_resolve',{id:p.id,result:'not_published'},ctx);assert.equal(tables.posts.find(x=>x.id===p.id).status,'failed');});
test('revoked and expired Bearer tokens cannot authenticate',async()=>{const token='sp_test-secret';tables.api_keys.push({id:randomUUID(),owner_id:owner,token_hash:hash(token),brand_ids:[brand],scopes:['read'],expires_at:new Date(Date.now()+60000).toISOString(),revoked_at:null});const req=()=>new Request('https://app.example.com/mcp',{headers:{Authorization:'Bearer '+token}});assert.equal((await context(req(),{mcp:true})).ownerId,owner);tables.api_keys[0].revoked_at=new Date().toISOString();await assert.rejects(()=>context(req(),{mcp:true}),e=>e.status===401);tables.api_keys[0].revoked_at=null;tables.api_keys[0].expires_at='2000-01-01T00:00:00Z';await assert.rejects(()=>context(req(),{mcp:true}),e=>e.status===401);});
test('OAuth access is bound to this MCP resource',async()=>{const token='oauth-test';tables.oauth_grants.push({id:randomUUID(),access_hash:hash(token),owner_id:owner,brand_ids:[brand],scopes:['read'],expires_at:new Date(Date.now()+60000).toISOString(),revoked_at:null,resource:'https://another.example.com/mcp'});await assert.rejects(()=>context(new Request('https://app.example.com/mcp',{headers:{Authorization:'Bearer '+token}}),{mcp:true}),e=>e.status===401);});

test('a stale panel cannot approve or overwrite a newer draft',async()=>{const p=await execute('post_create',input(),ctx);const changed=await execute('post_update',{id:p.id,expected_updated_at:p.updated_at,title:'Changed',content:'New content',payload:{}},ctx);assert.notEqual(changed.updated_at,p.updated_at);await assert.rejects(()=>execute('post_approve',{id:p.id,expected_updated_at:p.updated_at},ctx),e=>e.status===409);await assert.rejects(()=>execute('post_update',{id:p.id,expected_updated_at:p.updated_at,title:'Stale',content:'Old content',payload:{}},ctx),e=>e.status===409);});

test('reschedule preserves approval and rejects stale, past, unauthorized and in-flight changes',async()=>{
 let p=await execute('post_create',input(),ctx);const future=new Date(Date.now()+86400000).toISOString();
 p=await execute('post_reschedule',{id:p.id,expected_updated_at:p.updated_at,scheduled_at:future},ctx);assert.equal(p.status,'approval');assert.equal(p.approved_at,null);
 p=await execute('post_approve',{id:p.id,expected_updated_at:p.updated_at},ctx);const approved=p.approved_at;
 p=await execute('post_reschedule',{id:p.id,expected_updated_at:p.updated_at,scheduled_at:future},ctx);assert.equal(p.status,'scheduled');assert.equal(p.approved_at,approved);
 const args={id:p.id,expected_updated_at:p.updated_at,scheduled_at:new Date(Date.now()+172800000).toISOString()};
 await assert.rejects(()=>execute('post_reschedule',args,{...ctx,actor:'agent',brandIds:[other]}),e=>e.status===403);
 await assert.rejects(()=>execute('post_reschedule',{...args,scheduled_at:'2000-01-01T00:00:00Z'},ctx));
 await assert.rejects(()=>execute('post_reschedule',{...args,expected_updated_at:'2000-01-01T00:00:00Z'},ctx),e=>e.status===409);
 for(const status of ['processing','published','uncertain']){tables.posts.find(x=>x.id===p.id).status=status;await assert.rejects(()=>execute('post_reschedule',args,ctx),e=>e.status===409);}
 assert.equal(tables.posts.find(x=>x.id===p.id).scheduled_at,future);
});
