import {randomUUID} from 'node:crypto';
import {execute} from '../lib/actions.mjs';
import test,{mock,after} from 'node:test';import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';import dns from 'node:dns/promises';import https from 'node:https';import{syncBuiltinESMExports}from'node:module';
import{encrypt}from'../lib/security.mjs';import{provider,publish,credentialAAD}from'../lib/providers.mjs';import{uploadFacebookImage,facebookPhotoIds}from'../lib/facebook-media.mjs';
process.env.ENCRYPTION_KEY='ab'.repeat(32);
const c={id:randomUUID(),owner_id:randomUUID(),brand_id:randomUUID(),platform:'facebook',external_id:'123'};c.credentials=encrypt({access_token:'test-token'},credentialAAD(c));const bytes=Buffer.from([255,216,255,224,0,16,1,2,3]);let replies=[],calls=[];
mock.method(dns,'lookup',async()=>[{address:'8.8.8.8',family:4}]);syncBuiltinESMExports();mock.method(https,'request',(url,options,cb)=>{const req=new EventEmitter(),chunks=[];req.write=b=>chunks.push(Buffer.from(b));req.end=()=>{calls.push({url:new URL(url),options,body:Buffer.concat(chunks)});const reply=replies.shift();assert.ok(reply,'unexpected network call');const res=new EventEmitter();res.statusCode=reply.status||200;res.headers={};queueMicrotask(()=>{cb(res);res.emit('data',reply.bytes||Buffer.from(JSON.stringify(reply.data)));res.emit('end');});};return req;});after(()=>{mock.restoreAll();syncBuiltinESMExports();});
const reset=r=>{replies=r;calls=[];};
test('upload sends actual binary multipart and produces a tenant-bound reference without publishing',async()=>{reset([{data:{id:'99'}}]);const r=await uploadFacebookImage(c,{data_base64:bytes.toString('base64')},provider);assert.equal(calls.length,1);assert.equal(calls[0].url.pathname,'/v25.0/123/photos');assert.match(calls[0].options.headers['Content-Type'],/^multipart\/form-data; boundary=/);assert.ok(calls[0].body.includes(bytes));assert.ok(calls[0].body.toString().includes('name="published"\r\n\r\nfalse'));assert.ok(calls[0].body.toString().includes('name="source"'));assert.equal(r.published,false);assert.deepEqual(facebookPhotoIds(c,r.facebook_media),['99']);assert.throws(()=>facebookPhotoIds({...c,external_id:'456'},r.facebook_media));assert.throws(()=>facebookPhotoIds({...c,owner_id:'other'},r.facebook_media));
 reset([{data:{id:'123_77'}}]);await publish(c,{content:'Text',payload:{facebook_media:r.facebook_media}});assert.equal(calls[0].url.pathname,'/v25.0/123/feed');assert.deepEqual(JSON.parse(calls[0].body).attached_media,[{media_fbid:'99'}]);});
test('URL images are fetched and uploaded as binary, then attached to a feed post',async()=>{reset([{bytes},{data:{id:'98'}},{data:{id:'123_76'}}]);const result=await publish(c,{content:'Text',payload:{image_urls:['https://image.example.com/a.jpg'],link:'https://example.com'}});assert.equal(result.external_id,'123_76');assert.equal(calls[0].url.hostname,'image.example.com');assert.equal(calls[0].options.headers.Authorization,undefined);assert.ok(calls[1].body.includes(bytes));const body=JSON.parse(calls[2].body);assert.deepEqual(body.attached_media,[{media_fbid:'98'}]);assert.match(body.message,/https:\/\/example.com/);});
test('a failed image upload never falls back to text-only publishing',async()=>{reset([{bytes},{status:400,data:{error:{code:190}}}]);await assert.rejects(()=>publish(c,{content:'Text',payload:{image_urls:['https://image.example.com/a.jpg']}}));assert.equal(calls.filter(x=>x.url.pathname.endsWith('/feed')).length,0);});
test('invalid files, source ambiguity and mismatched formats fail before network calls',async()=>{reset([]);await assert.rejects(()=>uploadFacebookImage(c,{data_base64:Buffer.from('<svg>not a jpeg</svg>').toString('base64')},provider));await assert.rejects(()=>uploadFacebookImage(c,{url:'https://example.com/a.jpg',data_base64:'YWJj'},provider));await assert.rejects(()=>publish(c,{content:'Text',payload:{image_urls:['https://example.com/a.jpg'],video_url:'https://example.com/a.mp4'}}));assert.equal(calls.length,0);});

test('post_id attaches the uploaded reference and invalidates approval; other accounts are rejected',async()=>{
 process.env.SUPABASE_URL='https://database.example.com';process.env.SUPABASE_SERVICE_ROLE_KEY='test-only';
 const p={id:randomUUID(),owner_id:c.owner_id,brand_id:c.brand_id,connection_id:c.id,title:'Title',content:'Body',payload:{},status:'draft',updated_at:'2026-01-01T00:00:00.000Z',approved_at:'2026-01-01T00:00:00Z'};
 const ctx={ownerId:c.owner_id,actor:'agent',brandIds:[c.brand_id],scopes:['draft']};let updates=0;
 mock.method(globalThis,'fetch',async(raw,opts={})=>{const u=new URL(raw),table=u.pathname.split('/').pop();if(table==='audit_log')return new Response('[]');if(table==='connections')return new Response(JSON.stringify([c]));if(table==='posts'){if(opts.method==='PATCH'){assert.equal(u.searchParams.get('updated_at'),'eq.'+p.updated_at);Object.assign(p,JSON.parse(opts.body));updates++;}return new Response(JSON.stringify([p]));}throw Error('Unexpected table');});
 reset([{data:{id:'55'}}]);const result=await execute('facebook_upload_image',{connection_id:c.id,post_id:p.id,data_base64:bytes.toString('base64')},ctx);
 assert.equal(updates,1);assert.equal(result.post.approved_at,null);assert.equal(result.post.status,'draft');assert.equal(result.post.content,'Body');assert.deepEqual(facebookPhotoIds(c,result.post.payload.facebook_media),['55']);
 p.connection_id=randomUUID();reset([]);await assert.rejects(()=>execute('facebook_upload_image',{connection_id:c.id,post_id:p.id,data_base64:bytes.toString('base64')},ctx),e=>e.status===403);assert.equal(calls.length,0);
});
