import test from 'node:test';
import assert from 'node:assert/strict';
import {encrypt,decrypt,equal,hash,challenge,publicUrl,publicIp,assertScope,bodyText,sameOrigin} from '../lib/security.mjs';
import {validateRedirect} from '../lib/oauth.mjs';
import {wpPath,redactProviderData,linkedInUploadUrl} from '../lib/providers.mjs';
import {parseFeed} from '../lib/worker.mjs';
process.env.ENCRYPTION_KEY='ab'.repeat(32);
process.env.APP_URL='https://app.example.com';
test('AES-GCM round trip and tenant-bound authenticated encryption',()=>{const sealed=encrypt({token:'private-value'},'owner:brand:wordpress');assert.deepEqual(decrypt(sealed,'owner:brand:wordpress'),{token:'private-value'});assert.throws(()=>decrypt(sealed,'other:brand:wordpress'));const parts=sealed.split('.');const bytes=Buffer.from(parts[2],'base64url');bytes[0]^=1;parts[2]=bytes.toString('base64url');assert.throws(()=>decrypt(parts.join('.'),'owner:brand:wordpress'));assert.ok(!sealed.includes('private-value'));});
test('PKCE matches RFC 7636 example',()=>assert.equal(challenge('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk'),'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM'));
test('constant-time comparison handles Unicode byte lengths',()=>{assert.equal(equal('é','aa'),false);assert.equal(equal('secret','secret'),true);assert.equal(equal('secret',undefined),false);assert.notEqual(hash('token1'),hash('token2'));});
test('SSRF: only public HTTPS names, no credentials, private IPs or alternate encodings',()=>{for(const value of ['http://example.com','https://127.0.0.1','https://0x7f000001','https://2130706433','https://[::1]','https://user:pass@example.com','https://example.com:444','https://localhost','https://host.internal','https://example.com/#secret'])assert.throws(()=>publicUrl(value),value);assert.equal(publicUrl('https://example.com/feed').hostname,'example.com');});
test('SSRF: IP policy rejects private, multicast and reserved networks',()=>{for(const ip of ['0.1.2.3','10.1.1.1','127.0.0.1','169.254.169.254','172.16.0.1','172.31.5.4','192.168.2.1','100.64.1.1','192.0.2.1','198.18.1.1','198.51.100.1','203.0.113.1','224.1.1.1','255.255.255.255','::ffff:127.0.0.1'])assert.equal(publicIp(ip),false,ip);assert.equal(publicIp('8.8.8.8'),true);});
test('scopes and brand restrictions both apply',()=>{const ctx={scopes:['read','draft'],brandIds:['one']};assertScope(ctx,'draft','one');assert.throws(()=>assertScope(ctx,'publish','one'));assert.throws(()=>assertScope(ctx,'draft','two'));});
test('OAuth redirects are exact, never prefix matched',()=>{process.env.MCP_ALLOWED_REDIRECT_URIS='https://chatgpt.com/connector_platform_oauth_redirect';assert.equal(validateRedirect('https://chatgpt.com/connector_platform_oauth_redirect'),'https://chatgpt.com/connector_platform_oauth_redirect');for(const u of ['https://chatgpt.com.evil.example/callback','https://chatgpt.com/connector_platform_oauth_redirect?next=evil','http://chatgpt.com/connector_platform_oauth_redirect'])assert.throws(()=>validateRedirect(u));});
test('WordPress REST path rejects traversal and arbitrary URLs',()=>{assert.equal(wpPath('wp/v2/posts/15'),'wp/v2/posts/15');assert.equal(wpPath('wp/v2/users/me'),'wp/v2/users/me');for(const path of ['https://evil.example','wp/v2/posts/../users','wp/v2/posts/%2e%2e/users','wp/v2/posts?x=1','wp/v2/posts//15'])assert.throws(()=>wpPath(path));});
test('RSS extracts content as untrusted plain data and rejects DTD',()=>{assert.deepEqual(parseFeed('<rss><item><guid>a</guid><title><![CDATA[Hello <b>world</b>]]></title><link>https://example.com/a</link><description>A &amp; B</description></item></rss>'),[{id:'a',title:'Hello world',link:'https://example.com/a',excerpt:'A & B'}]);assert.throws(()=>parseFeed('<!DOCTYPE rss [<!ENTITY x SYSTEM "file:///etc/passwd">]><rss/>'));});
test('request streaming enforces size even without Content-Length',async()=>{const req=new Request('https://app.example.com',{method:'POST',body:'a'.repeat(101)});await assert.rejects(()=>bodyText(req,100),e=>e.status===413);});
test('cookie mutations require exact configured Origin',()=>{sameOrigin(new Request('https://app.example.com',{headers:{Origin:'https://app.example.com'}}));assert.throws(()=>sameOrigin(new Request('https://app.example.com',{headers:{Origin:'https://evil.example'}})));assert.throws(()=>sameOrigin(new Request('https://app.example.com')));});

test('platform pagination does not expose credential parameters',()=>{const d=redactProviderData({data:[{access_token:'private',message:'hello'}],paging:{next:'https://graph.facebook.com/v25.0/feed?after=abc&access_token=private&appsecret_proof=secret'}});assert.ok(!JSON.stringify(d).includes('private'));assert.ok(!JSON.stringify(d).includes('secret'));assert.equal(new URL(d.paging.next).searchParams.get('after'),'abc');});

test('LinkedIn upload cannot send account tokens to a foreign host',()=>{assert.equal(new URL(linkedInUploadUrl('https://www.linkedin.com/dms-uploads/image?ut=signed')).hostname,'www.linkedin.com');for(const u of ['https://evil.example/dms-uploads/image','https://www.linkedin.com.evil.example/dms-uploads/image','https://www.linkedin.com/other/path'])assert.throws(()=>linkedInUploadUrl(u));});
