'use client';
import {useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,Plus} from 'lucide-react';
import {Row,platformNames,platformSymbols} from './types';
import {calendarDay,movablePost,movedDate} from '../lib/calendar.mjs';
export default function Calendar({month,setMonth,posts,conn,onPost,onNew,onMove,busy}:{month:Date;setMonth:(d:Date)=>void;posts:Row[];conn:(id:string)=>Row|undefined;onPost:(p:Row)=>void;onNew:()=>void;onMove:(p:Row,date:string)=>Promise<void>;busy:boolean}){
 const [moving,setMoving]=useState<string|null>(null),[hover,setHover]=useState(''),[message,setMessage]=useState('');const lock=useRef(false);
 const first=new Date(month.getFullYear(),month.getMonth(),1),start=new Date(first);start.setDate(first.getDate()-(first.getDay()+6)%7);
 const days=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});
 async function move(id:string,day:string){if(lock.current||busy)return;const p=posts.find(x=>x.id===id);if(!p||!movablePost(p))return;lock.current=true;setHover('');try{const date=movedDate(p.scheduled_at,day);if(Date.parse(date)<=Date.now())throw new Error('Wybierz datę w przyszłości.');if(date!==p.scheduled_at)await onMove(p,date);setMessage('Zapisano nowy termin.');setMoving(null);}catch(e){setMessage((e as Error).message);}finally{lock.current=false;}}
 return <section className="panel calendar-panel"><div className="section-title"><h2>{month.toLocaleDateString('pl-PL',{month:'long',year:'numeric'})}</h2><div className="calendar-nav"><button className="icon-button" aria-label="Poprzedni miesiąc" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={20}/></button><button className="text-button" onClick={()=>setMonth(new Date())}>Dzisiaj</button><button className="icon-button" aria-label="Następny miesiąc" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={20}/></button></div></div>
 <p className="calendar-note">Przeciągnij wpis na nowy dzień — godzina pozostanie ta sama. Możesz też wybrać „Przenieś”, a następnie dzień. Strefa: {Intl.DateTimeFormat().resolvedOptions().timeZone}. Kalendarz pokazuje pobraną kolejkę MCPLinker.</p>
 {moving&&<p>Wybierz nowy dzień. <button className="text-button" onClick={()=>setMoving(null)}>Anuluj przenoszenie</button></p>}<p className="calendar-note" role="status" aria-live="polite">{message}</p>
 <div className="calendar-grid">{['Pon','Wt','Śr','Czw','Pt','Sob','Niedz'].map(d=><div className="day-label" key={d}>{d}</div>)}{days.map(d=>{const day=calendarDay(d);return <div key={day} data-calendar-day={day} className={'day '+(d.getMonth()!==month.getMonth()?'outside ':'')+(day===calendarDay(new Date())?'today ':'')+(hover===day?'drop-target':'')}
 onDragOver={e=>{if(moving&&!busy){e.preventDefault();e.dataTransfer.dropEffect='move';setHover(day);}}} onDragLeave={()=>setHover('')} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-mcplinker-post');if(id&&id===moving)void move(id,day);}}>
 <div className="calendar-day-head"><button className="calendar-day" disabled={!moving||busy} aria-label={'Przenieś na '+day} onClick={()=>moving&&void move(moving,day)}>{d.getDate()}</button><button className="icon-button" aria-label={'Dodaj wpis '+d.toLocaleDateString()} onClick={onNew}><Plus size={13}/></button></div>
 {posts.filter(p=>p.scheduled_at&&calendarDay(new Date(p.scheduled_at))===day).map(p=>{const platform=conn(p.connection_id)?.platform||'wordpress';return <div key={p.id} data-post-id={p.id}><button className={'calendar-post '+p.status} draggable={movablePost(p)&&!busy} onDragStart={e=>{setMoving(p.id);e.dataTransfer.setData('application/x-mcplinker-post',p.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{setHover('');setMoving(null);}} onClick={()=>onPost(p)}><span><span className={'platform '+platform} title={platformNames[platform]}>{platformSymbols[platform]}</span>{new Date(p.scheduled_at).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}</span><strong>{p.title||p.content}</strong></button>{movablePost(p)&&<button className="calendar-move" disabled={busy} onClick={()=>{setMoving(p.id);setMessage('');}}>Przenieś</button>}</div>;})}</div>;})}</div></section>;
}
