import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {AppError,assertScope,encrypt,hash,random,scopes,safeFetch,publicUrl,cleanError} from './security.mjs';
import {db,owned,audit,configuration} from './db.mjs';
import {credentialAAD,testConnection,publish,platformRead,comment,provider,removeRemote,wpPath,uploadLinkedInImage} from './providers.mjs';
const uuid=z.string().uuid(),str=z.string().trim().min(1),brand={brand_id:uuid},id={id:uuid};
const page={limit:z.number().int().min(1).max(100).default(50),offset:z.number().int().min(0).default(0)};
export const registry={};
function action(name,scope,description,shape,handler,extra={}){registry[name]={name,scope,description,schema:z.object(shape).strict(),handler,...extra};}
const now=()=>new Date().toISOString();
const list=(table,ctx,query={})=>db(table,{query:{owner_id:'eq.'+ctx.ownerId,...(ctx.brandIds!==null?{[table==='brands'?'id':'brand_id']:'in.('+ctx.brandIds.join(',')+')'}:{}),...query}});
export function stable(v){return JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);}
async function brandOwned(ctx,brand_id,scope='read'){assertScope(ctx,scope,brand_id);return owned('brands',brand_id,ctx);}
async function connection(ctx,connection_id,scope='read'){const c=await owned('connections',connection_id,ctx);assertScope(ctx,scope,c.brand_id);return c;}
async function post(ctx,post_id,scope='read'){const p=await owned('posts',post_id,ctx);assertScope(ctx,scope,p.brand_id);return p;}
async function cas(p,body){const rows=await db('posts',{method:'PATCH',query:{id:'eq.'+p.id,owner_id:'eq.'+p.owner_id,status:'eq.'+p.status,updated_at:'eq.'+p.updated_at},body:{...body,updated_at:new Date(Math.max(Date.now(),Date.parse(p.updated_at)+1)).toISOString()}});if(!rows.length)throw new AppError('Wpis został zmieniony. Odśwież dane.',409);return rows[0];}
const editable=p=>{if(!['draft','approval','failed','cancelled'].includes(p.status))throw new AppError('Ten wpis jest zablokowany do edycji. Anuluj planowanie lub sprawdź wynik publikacji.',409);};
const connectionFields='id,owner_id,brand_id,platform,name,external_id,base_url,scopes,status,expires_at,last_checked_at,created_at';
action('brand_list','read','Lista dostępnych marek.',{},(_,c)=>list('brands',c,{order:'created_at.asc'}));
action('brand_create','manage','Utwórz markę z zasadami komunikacji.',{name:str.max(120),color:z.string().regex(/^#[a-f0-9]{6}$/i).default('#c9fa75'),website:z.string().url().optional(),voice:z.string().max(10000).default(''),timezone:z.string().default('Europe/Warsaw')},async(a,c)=>{if(c.brandIds!==null)throw new AppError('Nowe marki można dodawać w panelu.',403);try{new Intl.DateTimeFormat('pl',{timeZone:a.timezone});}catch{throw new AppError('Nieprawidłowa strefa czasowa.');}return(await db('brands',{method:'POST',body:{...a,owner_id:c.ownerId}}))[0];},{panelOnly:true});
action('brand_update','manage','Zmień profil i zasady zatwierdzania marki.',{...id,name:str.max(120),voice:z.string().max(10000),publish_policy:z.enum(['approval','automatic'])},async(a,c)=>{await brandOwned(c,a.id,'manage');const{id,...changes}=a;return(await db('brands',{method:'PATCH',query:{id:'eq.'+id,owner_id:'eq.'+c.ownerId},body:changes}))[0];},{panelOnly:true});
action('connection_list','read','Konta dostępne dla agenta, bez poświadczeń.',{},(_,c)=>list('connections',c,{select:connectionFields,order:'created_at.asc'}));
export async function saveConnection(ctx,data,secrets){await brandOwned(ctx,data.brand_id,'admin');const c={...data,owner_id:ctx.ownerId};c.credentials=encrypt(secrets,credentialAAD(c));await testConnection(c);const rows=await db('connections',{method:'POST',query:{on_conflict:'owner_id,brand_id,platform,external_id',select:connectionFields},prefer:'resolution=merge-duplicates,return=representation',body:{...c,status:'connected',last_checked_at:now()}});return rows[0];}
action('connect_wordpress','admin','Połącz WordPress przez hasło aplikacji.',{...brand,name:str.max(120),url:z.string().url(),username:str,password:str.max(500)},(a,c)=>saveConnection(c,{brand_id:a.brand_id,name:a.name,platform:'wordpress',base_url:publicUrl(a.url).href.replace(/\/$/,''),external_id:publicUrl(a.url).href.replace(/\/$/,'')},{username:a.username,password:a.password}),{panelOnly:true});
action('connect_token','admin','Połącz stronę Facebook lub konto LinkedIn.',{...brand,name:str.max(120),platform:z.enum(['facebook','linkedin']),external_id:str,access_token:str.max(10000),expires_at:z.string().datetime().optional()},(a,c)=>{if(a.platform==='facebook'&&!/^\d+$/.test(a.external_id)||a.platform==='linkedin'&&!/^urn:li:(person|organization):[a-zA-Z0-9_-]+$/.test(a.external_id))throw new AppError('Nieprawidłowy identyfikator konta.');return saveConnection(c,{brand_id:a.brand_id,name:a.name,platform:a.platform,external_id:a.external_id,expires_at:a.expires_at},{access_token:a.access_token});},{panelOnly:true});
action('connection_test','read','Sprawdź uprawnienia połączenia.',{...id},async(a,c)=>testConnection(await connection(c,a.id)));
action('connection_delete','admin','Odłącz konto i usuń jego lokalne wpisy.',{...id},async(a,c)=>{const item=await connection(c,a.id,'admin');if((await db('posts',{query:{connection_id:'eq.'+item.id,status:'eq.processing',limit:1}})).length)throw new AppError('Trwa publikacja. Poczekaj na wynik.',409);await db('connections',{method:'DELETE',query:{id:'eq.'+a.id,owner_id:'eq.'+c.ownerId}});return{deleted:true};},{panelOnly:true,destructive:true});
action('post_list','read','Lista wpisów; pobieraj kolejne strony przez offset.',{brand_id:uuid.optional(),status:z.enum(['draft','approval','scheduled','processing','published','failed','uncertain','cancelled']).optional(),...page},(a,c)=>{if(a.brand_id)assertScope(c,'read',a.brand_id);return list('posts',c,{...(a.brand_id?{brand_id:'eq.'+a.brand_id}:{}),...(a.status?{status:'eq.'+a.status}:{}),limit:a.limit,offset:a.offset,order:'created_at.desc'});});
const payload=z.object({type:z.enum(['post','page']).optional(),link:z.string().url().optional(),image_urls:z.array(z.string().url()).max(10).optional(),video_url:z.string().url().optional(),media_urn:z.string().regex(/^urn:li:(image|video|document):[a-zA-Z0-9_-]+$/).optional(),description:z.string().max(2000).optional(),alt_text:z.string().max(4086).optional(),date_gmt:z.string().datetime().optional(),excerpt:z.string().max(10000).optional(),slug:z.string().max(200).optional(),featured_media:z.number().int().positive().optional(),categories:z.array(z.number().int().positive()).optional(),tags:z.array(z.number().int().positive()).optional(),meta:z.record(z.unknown()).optional()}).strict();
const contentShape={title:z.string().max(300).default(''),content:str.max(100000),payload:payload.default({})};
action('post_create','draft','Zapisz szkic. dedupe_key musi być stały dla ponawianego żądania.',{...brand,connection_id:uuid,...contentShape,dedupe_key:str.max(180)},async(a,c)=>{await brandOwned(c,a.brand_id,'draft');const target=await connection(c,a.connection_id,'draft');if(target.brand_id!==a.brand_id)throw new AppError('Konto należy do innej marki.',403);if(target.platform==='linkedin'&&a.content.length>3000)throw new AppError('Tekst LinkedIn może mieć maksymalnie 3000 znaków.');const previous=await db('posts',{query:{owner_id:'eq.'+c.ownerId,dedupe_key:'eq.'+a.dedupe_key,limit:1}});if(previous[0]){if(['brand_id','connection_id','title','content','payload'].some(k=>stable(previous[0][k])!==stable(a[k])))throw new AppError('Ten dedupe_key został użyty dla innej treści.',409);return previous[0];}return(await db('posts',{method:'POST',body:{...a,owner_id:c.ownerId}}))[0];});
action('post_update','draft','Edytuj szkic. Zmiana treści unieważnia zatwierdzenie.',{...id,expected_updated_at:z.string().datetime(),...contentShape},async(a,c)=>{const p=await post(c,a.id,'draft');if(p.updated_at!==a.expected_updated_at)throw new AppError('Treść zmieniła się od otwarcia edytora. Odśwież wpis.',409);editable(p);return cas(p,{title:a.title,content:a.content,payload:a.payload,approved_at:null,approved_by:null,status:'draft',scheduled_at:null,error:null});});
action('post_approve','publish','Zatwierdź bieżącą wersję wpisu.',{...id,expected_updated_at:z.string().datetime()},async(a,c)=>{const p=await post(c,a.id,'publish');if(p.updated_at!==a.expected_updated_at)throw new AppError('Treść zmieniła się od ostatniego odczytu. Sprawdź ją ponownie.',409);editable(p);return cas(p,{approved_at:now(),approved_by:c.ownerId,status:'draft'});},{panelOnly:true});
export async function deliver(ctx,p){const c=await connection(ctx,p.connection_id,'publish');const b=await brandOwned(ctx,p.brand_id,'publish');if(b.publish_policy==='approval'&&!p.approved_at){return(await db('posts',{method:'PATCH',query:{id:'eq.'+p.id,lock_token:'eq.'+p.lock_token},body:{status:'approval',lock_token:null,locked_at:null,updated_at:now()}}))[0];}let started=false;try{await audit(ctx,'publish_started','started',p.brand_id,{post_id:p.id});started=true;const result=await publish(c,p);const updated=await db('posts',{method:'PATCH',query:{id:'eq.'+p.id,lock_token:'eq.'+p.lock_token,status:'eq.processing'},body:{...result,status:'published',error:null,locked_at:null,lock_token:null,updated_at:now()}});if(!updated.length)throw new AppError('Nie zapisano potwierdzenia.',503,'uncertain');return updated[0];}catch(e){const uncertain=started&&(!(e instanceof AppError)||e.code!=='provider_rejected');const status=uncertain?'uncertain':'failed';await db('posts',{method:'PATCH',query:{id:'eq.'+p.id,lock_token:'eq.'+p.lock_token},body:{status,error:cleanError(e),lock_token:null,locked_at:null,updated_at:now()}}).catch(()=>{});throw new AppError(uncertain?'Nie można potwierdzić wyniku. Sprawdź platformę przed ponowieniem.':cleanError(e),502,status);}}
async function queue(a,c,immediate){const p=await post(c,a.id,'publish');editable(p);const b=await brandOwned(c,p.brand_id,'publish');if(b.publish_policy==='approval'&&!p.approved_at)return cas(p,{status:'approval',scheduled_at:immediate?null:a.scheduled_at});if(!immediate){if(Date.parse(a.scheduled_at)<=Date.now())throw new AppError('Wybierz datę w przyszłości.');return cas(p,{status:'scheduled',scheduled_at:a.scheduled_at,error:null});}return deliver(c,await cas(p,{status:'processing',lock_token:randomUUID(),locked_at:now(),attempts:p.attempts+1,error:null}));}
action('post_schedule','publish','Zaplanuj publikację w ISO 8601 UTC. Polityka marki może wymagać zatwierdzenia.',{...id,scheduled_at:z.string().datetime()},(a,c)=>queue(a,c,false));
action('post_publish','publish','Opublikuj teraz, jeżeli polityka marki pozwala.',{...id},(a,c)=>queue(a,c,true));
action('post_cancel','publish','Anuluj oczekującą publikację.',{...id},async(a,c)=>{const p=await post(c,a.id,'publish');if(!['scheduled','approval','draft'].includes(p.status))throw new AppError('Nie można anulować tego stanu.',409);return cas(p,{status:'cancelled',scheduled_at:null});});
action('post_resolve','publish','Oznacz niepewną publikację po ręcznym sprawdzeniu platformy.',{...id,result:z.enum(['published','not_published']),external_id:str.optional(),external_url:z.string().url().optional()},async(a,c)=>{const p=await post(c,a.id,'publish');if(p.status!=='uncertain')throw new AppError('Wpis nie ma niepewnego wyniku.');if(a.result==='published'&&!a.external_id)throw new AppError('Podaj identyfikator potwierdzonej publikacji.');return cas(p,{status:a.result==='published'?'published':'failed',external_id:a.external_id||null,external_url:a.external_url||null,error:null});},{panelOnly:true});
action('post_delete_remote','admin','Usuń opublikowany wpis z platformy; WordPress przenosi do kosza.',{...id},async(a,c)=>{const p=await post(c,a.id,'admin');if(p.status!=='published')throw new AppError('Wpis nie jest opublikowany.');const result=await removeRemote(await connection(c,p.connection_id,'admin'),p);await cas(p,{status:'cancelled'});return result;},{destructive:true});
action('platform_read','read','Pobierz wpisy, komentarze lub dostępne statystyki platformy.',{connection_id:uuid,resource:z.enum(['posts','comments','insights']),external_id:str.optional(),limit:z.number().int().min(1).max(100).default(25),page:z.number().int().min(1).default(1)},async(a,c)=>platformRead(await connection(c,a.connection_id),a));
action('comment_create','engage','Dodaj publiczny komentarz pod wpisem zarządzanego konta.',{connection_id:uuid,external_id:str,message:str.max(10000)},async(a,c)=>comment(await connection(c,a.connection_id,'engage'),a.external_id,a.message));
action('wordpress_request','admin','WordPress core REST API: treści, taksonomie, użytkownicy, ustawienia, wtyczki i motywy. Zapisy wykonują się natychmiast, poza kolejką akceptacji.',{connection_id:uuid,path:str,method:z.enum(['GET','POST','PUT','PATCH','DELETE']).default('GET'),query:z.record(z.union([z.string(),z.number(),z.boolean()])).default({}),body:z.record(z.unknown()).optional()},async(a,c)=>{const target=await connection(c,a.connection_id,'admin');if(target.platform!=='wordpress')throw new AppError('Wybierz konto WordPress.');wpPath(a.path);return(await provider(target,a.path,{method:a.method,body:a.body,query:a.query})).data;},{destructive:true});
action('wordpress_upload_media','draft','Pobierz publiczny obraz HTTPS i dodaj do biblioteki WordPress (do 8 MB).',{connection_id:uuid,url:z.string().url(),filename:z.string().regex(/^[a-zA-Z0-9_-]+\.(jpg|jpeg|png|webp)$/),alt:z.string().max(1000).default('')},async(a,c)=>{const target=await connection(c,a.connection_id,'draft');if(target.platform!=='wordpress')throw new AppError('Wybierz WordPress.');const r=await safeFetch(a.url);const mime=r.headers.get('content-type')?.split(';')[0];if(!r.ok||!['image/jpeg','image/png','image/webp'].includes(mime))throw new AppError('Wymagany obraz JPG, PNG lub WebP.');const media=await provider(target,'wp/v2/media',{method:'POST',binary:r.bytes,headers:{'Content-Type':mime,'Content-Disposition':`attachment; filename="${a.filename}"`}});if(a.alt)await provider(target,'wp/v2/media/'+media.data.id,{method:'POST',body:{alt_text:a.alt}});return media.data;});
action('linkedin_upload_image','draft','Prześlij publiczny obraz JPG, PNG lub GIF do LinkedIn (do 8 MB); otrzymany media_urn dodaj do szkicu.',{connection_id:uuid,url:z.string().url()},async(a,c)=>uploadLinkedInImage(await connection(c,a.connection_id,'draft'),a.url));
action('wordpress_read','read','Odczytaj treści WordPress bez uprawnień administracyjnych.',{connection_id:uuid,resource:z.enum(['posts','pages','media','comments','categories','tags','search','types','taxonomies','statuses']),id:z.number().int().positive().optional(),search:z.string().max(200).optional(),page:z.number().int().min(1).default(1),per_page:z.number().int().min(1).max(100).default(25),status:z.enum(['publish','draft','pending','future','private','trash']).optional()},async(a,c)=>{const target=await connection(c,a.connection_id);if(target.platform!=='wordpress')throw new AppError('Wybierz konto WordPress.');return(await provider(target,'wp/v2/'+a.resource+(a.id?'/'+a.id:''),{query:{context:'view',...(!a.id?{page:a.page,per_page:a.per_page,search:a.search,status:a.status}:{})}})).data;});
action('asset_list','read','Lista mediów marki.',{...page},(a,c)=>list('assets',c,{limit:a.limit,offset:a.offset,order:'created_at.desc'}));
action('asset_create','draft','Zapisz odnośnik do publicznego pliku.',{...brand,name:str,url:z.string().url(),mime_type:str.default('image/jpeg'),alt:z.string().default('')},async(a,c)=>{await brandOwned(c,a.brand_id,'draft');publicUrl(a.url);return(await db('assets',{method:'POST',body:{...a,owner_id:c.ownerId}}))[0];});
const automationConfig=z.object({source_url:z.string().url().optional(),source_connection_id:uuid.optional(),targets:z.array(uuid).min(1).max(30),template:z.string().min(1).max(10000).default('{title}\n\n{link}'),interval_minutes:z.number().int().min(5).max(43200).default(60)}).strict();
action('automation_list','read','Lista reguł przygotowania szkiców.',{},(_,c)=>list('automations',c,{order:'created_at.desc'}));
action('automation_create','manage','RSS lub WordPress → szkice dla wybranych kont. Nie publikuje samodzielnie.',{...brand,name:str,kind:z.enum(['rss_to_draft','wordpress_to_social']),config:automationConfig},async(a,c)=>{await brandOwned(c,a.brand_id,'manage');if(a.kind==='rss_to_draft'){if(!a.config.source_url)throw new AppError('Podaj adres RSS.');publicUrl(a.config.source_url);}else{const source=await connection(c,a.config.source_connection_id,'manage');if(source.platform!=='wordpress'||source.brand_id!==a.brand_id)throw new AppError('Wybierz WordPress tej samej marki.');}for(const target of a.config.targets){if((await connection(c,target,'manage')).brand_id!==a.brand_id)throw new AppError('Konta docelowe muszą należeć do marki.');}return(await db('automations',{method:'POST',body:{...a,owner_id:c.ownerId}}))[0];});
action('automation_toggle','manage','Włącz lub wyłącz regułę przygotowania szkiców.',{...id,enabled:z.boolean()},async(a,c)=>{const item=await owned('automations',a.id,c);assertScope(c,'manage',item.brand_id);return(await db('automations',{method:'PATCH',query:{id:'eq.'+a.id,owner_id:'eq.'+c.ownerId},body:{enabled:a.enabled,next_run_at:now()}}))[0];});
action('agent_list','admin','Lista tokenów agentów bez sekretów.',{},(_,c)=>db('api_keys',{query:{owner_id:'eq.'+c.ownerId,select:'id,name,prefix,scopes,brand_ids,expires_at,revoked_at,created_at',order:'created_at.desc'}}),{panelOnly:true});
action('agent_create','admin','Utwórz ograniczony token agenta. Wartość jest pokazywana raz.',{name:str.max(120),scopes:z.array(z.enum(scopes)).min(1),brand_ids:z.array(uuid).min(1),expires_at:z.string().datetime()},async(a,c)=>{if(Date.parse(a.expires_at)<=Date.now())throw new AppError('Termin ważności musi być w przyszłości.');for(const b of a.brand_ids)await brandOwned(c,b,'admin');const token='sp_'+random();const row=(await db('api_keys',{method:'POST',query:{select:'id,name,prefix,scopes,brand_ids,expires_at'},body:{...a,owner_id:c.ownerId,token_hash:hash(token),prefix:token.slice(0,11)}}))[0];return{...row,token};},{panelOnly:true});
action('agent_revoke','admin','Unieważnij token agenta.',{...id},async(a,c)=>{await owned('api_keys',a.id,c);await db('api_keys',{method:'PATCH',query:{id:'eq.'+a.id,owner_id:'eq.'+c.ownerId},body:{revoked_at:now()}});return{revoked:true};},{panelOnly:true});
action('grant_list','admin','Lista autoryzacji OAuth ChatGPT.',{},(_,c)=>db('oauth_grants',{query:{owner_id:'eq.'+c.ownerId,select:'id,client_id,scopes,brand_ids,expires_at,refresh_expires_at,revoked_at,created_at'}}),{panelOnly:true});
action('grant_revoke','admin','Unieważnij autoryzację ChatGPT.',{...id},async(a,c)=>{await owned('oauth_grants',a.id,c);await db('oauth_grants',{method:'PATCH',query:{id:'eq.'+a.id,owner_id:'eq.'+c.ownerId},body:{revoked_at:now()}});return{revoked:true};},{panelOnly:true});
action('provider_app_save','admin','Zapisz konfigurację aplikacji OAuth Meta lub LinkedIn.',{platform:z.enum(['facebook','linkedin']),client_id:str,client_secret:str,scopes:z.array(str).min(1)},async(a,c)=>{await db('provider_apps',{method:'POST',query:{on_conflict:'owner_id,platform'},prefer:'resolution=merge-duplicates,return=representation',body:{owner_id:c.ownerId,platform:a.platform,encrypted_config:encrypt(a,c.ownerId+':'+a.platform)}});return{saved:true};},{panelOnly:true});
action('diagnostics','read','Stan konfiguracji serwera bez sekretów.',{},()=>({configuration:configuration(),scheduler:'Domyślny harmonogram Vercel: raz dziennie o 06:00 UTC. Publikacja w dokładnej minucie wymaga częstszego wyzwalania /api/cron.',api_versions:{facebook:process.env.META_API_VERSION||'v25.0',linkedin:process.env.LINKEDIN_API_VERSION||'202609'}}),{panelOnly:true});
action('audit_list','read','Historia działań agentów i panelu.',{...page},(a,c)=>list('audit_log',c,{limit:a.limit,offset:a.offset,order:'created_at.desc'}));
export async function execute(name,args,ctx){const a=registry[name];if(!a)throw new AppError('Nieznana operacja.',404);if(a.panelOnly&&ctx.actor!=='panel')throw new AppError('Ta operacja wymaga panelu właściciela.',403);assertScope(ctx,a.scope);const parsed=a.schema.safeParse(args);if(!parsed.success)throw new AppError('Nieprawidłowe parametry: '+parsed.error.issues.map(i=>i.path.join('.')+': '+i.message).join('; '));let result;try{result=await a.handler(parsed.data,ctx);}catch(e){if(a.scope!=='read')await audit(ctx,name,'error',parsed.data.brand_id||null,{code:e instanceof AppError?e.code:'internal_error'}).catch(()=>{});throw e;}if(a.scope!=='read')await audit(ctx,name,'success',parsed.data.brand_id||result?.brand_id||null,{id:result?.id||null}).catch(()=>{});return result;}
