import {z} from 'zod';
import {configuration,db,rpc} from './db.mjs';
import {context,authRequest,sessionCookies,cookie} from './auth.mjs';
import {AppError,json,origin,sameOrigin,bodyJson,equal,hash,cleanError} from './security.mjs';
import {execute} from './actions.mjs';
import {runWorker} from './worker.mjs';
import {providerOAuth} from './provider-oauth.mjs';
export async function handleApi(req){try{const url=new URL(req.url),path=url.pathname;
 if(path==='/api/status'&&req.method==='GET')return json({configured:configuration().every(i=>i.ready),configuration:configuration(),name:'MCPLinker'});
 if(path==='/api/cron'&&['GET','POST'].includes(req.method)){if(!process.env.CRON_SECRET||!equal(req.headers.get('authorization'), 'Bearer '+process.env.CRON_SECRET))throw new AppError('Brak dostępu.',401);return json(await runWorker());}
 if(path.startsWith('/api/connect/')&&req.method==='GET'){try{return await providerOAuth(req);}catch(e){return Response.redirect(origin()+'/?view=connections&connect_error='+encodeURIComponent(cleanError(e)),302);}}
 if(req.method!=='GET')sameOrigin(req);
 if(path.startsWith('/api/auth/')&&req.method==='POST'){const mode=path.split('/').pop();if(mode==='refresh'){const refresh_token=cookie(req,'sp_refresh');if(!refresh_token)throw new AppError('Zaloguj się ponownie.',401);const d=await authRequest('token?grant_type=refresh_token',{refresh_token});return sessionCookies(json({ok:true}),d);}if(mode==='logout'){const access=cookie(req,'sp_access');if(access)await authRequest('logout',{scope:'local'},access).catch(()=>{});const r=json({ok:true});for(const[name,p]of [['sp_access','/'],['sp_refresh','/api/auth']])r.headers.append('Set-Cookie',`${name}=; Path=${p}; HttpOnly; SameSite=Lax; Max-Age=0${origin().startsWith('https:')?'; Secure':''}`);return r;}if(!['login','signup'].includes(mode))throw new AppError('Nieznana operacja.',404);const a=z.object({email:z.string().email(),password:z.string().min(mode==='signup'?12:1).max(512)}).strict().parse(await bodyJson(req,16384));if(!process.env.APP_OWNER_EMAIL||a.email.toLowerCase()!==process.env.APP_OWNER_EMAIL.toLowerCase())throw new AppError('Nieprawidłowe dane właściciela.',401);if(!await rpc('take_rate',{p_key:'login:'+hash(a.email.toLowerCase()),p_limit:20,p_seconds:900}))throw new AppError('Zbyt wiele prób. Spróbuj za 15 minut.',429);const data=await authRequest(mode==='signup'?'signup':'token?grant_type=password',a);return data.access_token?sessionCookies(json({ok:true}),data):json({ok:true,confirmation_required:true});}
 const ctx=await context(req);if(ctx.actor!=='panel')throw new AppError('Użyj serwera /mcp dla dostępu agentów.',403);
 if(path==='/api/bootstrap'&&req.method==='GET'){const names=['brand_list','connection_list','post_list','automation_list','asset_list','agent_list','grant_list','audit_list'];const result=await Promise.all(names.map(n=>execute(n,n==='post_list'||n==='asset_list'||n==='audit_list'?{limit:100}:{},ctx)));return json(Object.fromEntries(names.map((n,i)=>[n,result[i]])));}
 if(path.startsWith('/api/action/')&&req.method==='POST')return json(await execute(path.slice('/api/action/'.length),await bodyJson(req),ctx));
 if(path==='/api/export'&&req.method==='GET'){const data={exported_at:new Date().toISOString()};for(const table of ['brands','posts','assets','automations','audit_log']){data[table]=[];for(let offset=0;;offset+=500){const rows=await db(table,{query:{owner_id:'eq.'+ctx.ownerId,limit:500,offset,order:'id.asc'}});data[table].push(...rows);if(rows.length<500)break;}}data.connections=await execute('connection_list',{},ctx);return json(data,200,{'Content-Disposition':'attachment; filename="mcplinker-export.json"'});}throw new AppError('Nie znaleziono.',404);
 }catch(e){return json({error:e instanceof z.ZodError?'Sprawdź pola formularza.':cleanError(e),code:e instanceof AppError?e.code:'internal_error'},e instanceof AppError?e.status:e instanceof z.ZodError?400:500);}}
