import {AppError} from './security.mjs';
export const configuration=()=>['APP_URL','APP_OWNER_EMAIL','SUPABASE_URL','SUPABASE_PUBLISHABLE_KEY','SUPABASE_SERVICE_ROLE_KEY','ENCRYPTION_KEY','CRON_SECRET'].map(key=>({key,ready:Boolean(process.env[key])}));
export function databaseHeaders(key){key=key.trim();if(key.startsWith('sb_publishable_'))throw new AppError('W SUPABASE_SERVICE_ROLE_KEY wpisano klucz publiczny. Użyj Secret key z tego samego projektu Supabase.',503,'database_credentials');return {apikey:key,...(key.startsWith('sb_secret_')?{}:{Authorization:'Bearer '+key})};}
export function databaseError(status,e={}){
 if(e.code==='23505')return new AppError('Ten element już istnieje.',409,'duplicate');
 if(status===401)return new AppError('Supabase odrzucił klucz serwerowy. Sprawdź SUPABASE_SERVICE_ROLE_KEY: pełny Secret key z tego samego projektu co SUPABASE_URL. Po zmianie wykonaj Redeploy w Vercel.',503,'database_credentials');
 if(status===403||e.code==='42501')return new AppError('Klucz Supabase nie ma uprawnień serwerowych. Sprawdź SUPABASE_SERVICE_ROLE_KEY i uprawnienia bazy.',503,'database_permissions');
 if(['PGRST202','PGRST205','42P01','42883'].includes(e.code))return new AppError('W bazie brakuje wymaganej tabeli lub funkcji. Sprawdź projekt wskazany przez SUPABASE_URL i instalację schematu MCPLinker.',503,'database_schema');
 return new AppError('Błąd operacji bazy danych. Sprawdź logi serwera: MCPLinker database request failed.',503,'database_error');
}
export async function db(table,{method='GET',query={},body,prefer='return=representation'}={}){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key||!process.env.SUPABASE_URL)throw new AppError('Uzupełnij konfigurację Supabase.',503,'setup_required');const u=new URL(process.env.SUPABASE_URL.trim().replace(/\/+$/,'')+'/rest/v1/'+table);for(const[k,v]of Object.entries(query))u.searchParams.set(k,String(v));const r=await fetch(u,{method,headers:{...databaseHeaders(key),'Content-Type':'application/json',Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000),cache:'no-store'});if(!r.ok){const e=await r.json().catch(()=>({}));console.error('MCPLinker database request failed',{status:r.status,code:typeof e.code==='string'&&/^[A-Z0-9]{5,10}$/.test(e.code)?e.code:'unknown'});throw databaseError(r.status,e);}const s=await r.text();return s?JSON.parse(s):null;}
export const rpc=(name,body)=>db('rpc/'+name,{method:'POST',body});
export async function owned(table,id,ctx){const a=await db(table,{query:{id:'eq.'+id,owner_id:'eq.'+ctx.ownerId,limit:1}});if(!a[0])throw new AppError('Nie znaleziono elementu.',404);return a[0];}
export const audit=(ctx,action,result,brand_id=null,details={})=>db('audit_log',{method:'POST',body:{owner_id:ctx.ownerId,brand_id,actor:ctx.actor,action,result,details}});
