import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {db,rpc} from './db.mjs';
import {context} from './auth.mjs';
import {brandAccess} from './brand-access.mjs';
import {AppError,bodyJson,bodyText,origin,json,random,hash,challenge,scopes,sameOrigin,cleanError,equal,sign} from './security.mjs';
const resource=()=>origin()+'/mcp';
// ChatGPT and Claude connector callbacks are always allowed; the variable adds exact callbacks of other clients.
const connectorRedirects=['https://chatgpt.com/connector_platform_oauth_redirect','https://claude.ai/api/mcp/auth_callback','https://claude.com/api/mcp/auth_callback'];
export const redirects=()=>new Set([...connectorRedirects,...(process.env.MCP_ALLOWED_REDIRECT_URIS||'').split(',').map(s=>s.trim()).filter(Boolean)]);
const secretMethods=['client_secret_post','client_secret_basic'];
// Derived from the client id, so confidential clients need no extra database column.
const clientSecret=id=>sign('oauth-client-secret:'+id);
async function rate(key,limit=100){if(!await rpc('take_rate',{p_key:key,p_limit:limit,p_seconds:3600}))throw new AppError('Zbyt wiele żądań. Spróbuj później.',429,'temporarily_unavailable');}
function clientId(v){if(!z.string().uuid().safeParse(v).success)throw new AppError('Nieprawidłowy klient.',400,'invalid_client');return v;}
function checkResource(v){if(v&&v.replace(/\/+$/,'')!==resource())throw new AppError('Nieprawidłowy resource.',400,'invalid_target');return resource();}
function credentials(req,a){const basic=req.headers.get('authorization')?.match(/^Basic ([A-Za-z0-9+/]+=*)$/i)?.[1];if(!basic)return[a.get('client_id'),a.get('client_secret')];const raw=Buffer.from(basic,'base64').toString(),i=raw.indexOf(':');try{return(i<0?[raw,'']:[raw.slice(0,i),raw.slice(i+1)]).map(v=>decodeURIComponent(v.replace(/\+/g,' ')));}catch{throw new AppError('Nieprawidłowe dane klienta.',401,'invalid_client');}}
// A secret, when sent in the body or as HTTP Basic, must match. PKCE and exact callbacks protect every client.
function authenticate(req,a){const[id,secret]=credentials(req,a),client=clientId(id);if(a.get('client_id')&&a.get('client_id')!==client||secret&&!equal(secret,clientSecret(client)))throw new AppError('Nieprawidłowe dane klienta.',401,'invalid_client');return client;}
export function validateRedirect(uri){if(!redirects().has(uri))throw new AppError('Adres przekierowania nie jest dozwolony.',400,'invalid_redirect_uri');return uri;}
// Unknown scopes, such as a client's own label, are ignored (RFC 6749 section 3.3).
async function authorize(params){const client_id=clientId(params.get('client_id'));const clients=await db('oauth_clients',{query:{client_id:'eq.'+client_id,limit:1}});const client=clients[0];const redirect_uri=validateRedirect(params.get('redirect_uri'));if(!client?.redirect_uris.includes(redirect_uri))throw new AppError('Nieprawidłowy adres klienta.',400,'invalid_client');if(params.get('response_type')!=='code'||params.get('code_challenge_method')!=='S256'||! /^[a-zA-Z0-9_-]{43}$/.test(params.get('code_challenge')||''))throw new AppError('Wymagane response_type=code i PKCE S256.',400,'invalid_request');const state=params.get('state')||'';if(state.length<16||state.length>2048)throw new AppError('Nieprawidłowy parametr state.');const requested=[...new Set((params.get('scope')||'').split(' ').filter(s=>scopes.includes(s)))];return{client,client_id,redirect_uri,state,challenge:params.get('code_challenge'),resource:checkResource(params.get('resource')),scopes:requested.length?requested:['read','draft']};}
// The owner may widen or narrow the requested scopes on the consent screen (RFC 6749 section 3.3).
function grantedScopes(value,requested){if(value===undefined)return requested;const r=z.array(z.enum(scopes)).safeParse(value);if(!r.success||!r.data.length)throw new AppError('Wybierz przynajmniej jedno uprawnienie.',400,'invalid_scope');return scopes.filter(s=>r.data.includes(s));}
function bearerTokens(access,refresh,requested){return{access_token:access,token_type:'Bearer',expires_in:3600,refresh_token:refresh,scope:requested.join(' ')};}
export async function handleOAuth(req){try{const u=new URL(req.url),p=u.pathname;if(req.method==='GET'&&p.startsWith('/.well-known/oauth-protected-resource'))return json({resource:resource(),authorization_servers:[origin()],scopes_supported:scopes,bearer_methods_supported:['header'],resource_name:'MCPLinker'});if(req.method==='GET'&&p==='/.well-known/oauth-authorization-server')return json({issuer:origin(),authorization_endpoint:origin()+'/oauth/authorize',token_endpoint:origin()+'/oauth/token',registration_endpoint:origin()+'/oauth/register',revocation_endpoint:origin()+'/oauth/revoke',response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['none',...secretMethods],code_challenge_methods_supported:['S256'],scopes_supported:scopes,authorization_response_iss_parameter_supported:true});
 if(req.method==='POST'&&p==='/oauth/register'){await rate('oauth:register');const a=z.object({client_name:z.string().min(1).max(120).default('ChatGPT'),redirect_uris:z.array(z.string().url()).min(1).max(5),token_endpoint_auth_method:z.enum(['none',...secretMethods]).default('none'),grant_types:z.array(z.enum(['authorization_code','refresh_token'])).optional(),response_types:z.array(z.literal('code')).optional()}).passthrough().parse(await bodyJson(req,16384));a.redirect_uris.forEach(validateRedirect);const id=randomUUID(),secret=secretMethods.includes(a.token_endpoint_auth_method)?{client_secret:clientSecret(id),client_secret_expires_at:0}:{};const row=(await db('oauth_clients',{method:'POST',body:{client_id:id,client_name:a.client_name,redirect_uris:a.redirect_uris}}))[0];return json({...row,...secret,client_id_issued_at:Math.floor(Date.now()/1000),token_endpoint_auth_method:a.token_endpoint_auth_method,grant_types:['authorization_code','refresh_token'],response_types:['code']},201);}
 if(req.method==='GET'&&p==='/oauth/authorize'){await authorize(u.searchParams);return Response.redirect(origin()+'/oauth/consent?'+u.searchParams,302);}
 if(req.method==='POST'&&['/oauth/details','/oauth/approve'].includes(p)){sameOrigin(req);const ctx=await context(req);if(ctx.actor!=='panel')throw new AppError('Zaloguj się do panelu.',403);const input=await bodyJson(req,16384);const a=await authorize(new URLSearchParams(input.query));if(p==='/oauth/details'){const brands=await db('brands',{query:{owner_id:'eq.'+ctx.ownerId,select:'id,name'}});return json({client_name:a.client.client_name,scopes:a.scopes,redirect_uri:a.redirect_uri,brands});}const target=new URL(a.redirect_uri);target.searchParams.set('state',a.state);target.searchParams.set('iss',origin());if(input.deny===true){target.searchParams.set('error','access_denied');return json({redirect:target.href});}const granted=grantedScopes(input.scopes,a.scopes),access=await brandAccess(input,ctx);const code=random();await db('oauth_codes',{method:'POST',body:{code_hash:hash(code),client_id:a.client_id,owner_id:ctx.ownerId,redirect_uri:a.redirect_uri,challenge:a.challenge,resource:a.resource,scopes:granted,...access,expires_at:new Date(Date.now()+300000).toISOString()}});target.searchParams.set('code',code);return json({redirect:target.href});}
 if(req.method==='POST'&&p==='/oauth/token'){const a=new URLSearchParams(await bodyText(req,16384));const client=authenticate(req,a);await rate('oauth:token:'+client,300);checkResource(a.get('resource'));const access=random(),refresh=random();if(a.get('grant_type')==='authorization_code'){const verifier=a.get('code_verifier')||'';if(!/^[a-zA-Z0-9._~-]{43,128}$/.test(verifier))throw new AppError('Nieprawidłowy PKCE.',400,'invalid_grant');const rows=await rpc('consume_oauth_code',{p_hash:hash(a.get('code')||''),p_client:client,p_redirect:validateRedirect(a.get('redirect_uri')),p_challenge:challenge(verifier),p_resource:resource()});const code=rows[0];if(!code)throw new AppError('Kod wygasł lub został wykorzystany.',400,'invalid_grant');await db('oauth_grants',{method:'POST',body:{owner_id:code.owner_id,client_id:client,access_hash:hash(access),refresh_hash:hash(refresh),resource:resource(),scopes:code.scopes,brand_ids:code.brand_ids,all_brands:code.all_brands===true,expires_at:new Date(Date.now()+3600000).toISOString(),refresh_expires_at:new Date(Date.now()+30*86400000).toISOString()}});return json(bearerTokens(access,refresh,code.scopes));}if(a.get('grant_type')==='refresh_token'){const rows=await rpc('rotate_oauth_token',{p_hash:hash(a.get('refresh_token')||''),p_client:client,p_resource:resource(),p_access:hash(access),p_refresh:hash(refresh)});if(!rows[0])throw new AppError('Token wygasł lub został wykorzystany.',400,'invalid_grant');return json(bearerTokens(access,refresh,rows[0].scopes));}throw new AppError('Nieobsługiwany grant.',400,'unsupported_grant_type');}
 if(req.method==='POST'&&p==='/oauth/revoke'){const a=new URLSearchParams(await bodyText(req,16384));const token=hash(a.get('token')||'');for(const column of ['access_hash','refresh_hash'])await db('oauth_grants',{method:'PATCH',query:{[column]:'eq.'+token},body:{revoked_at:new Date().toISOString()}});return new Response(null,{status:200,headers:{'Cache-Control':'no-store'}});}return json({error:'not_found'},404);
 }catch(e){return json({error:e instanceof AppError?e.code:'invalid_request',error_description:e instanceof z.ZodError?'Nieprawidłowe parametry klienta.':cleanError(e)},e instanceof AppError?e.status:400);}}
