import {AppError,decrypt,safeFetch,publicUrl} from './security.mjs';
export function redactProviderData(value){if(Array.isArray(value))return value.map(redactProviderData);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([k])=>!['access_token','refresh_token','client_secret','password'].includes(k.toLowerCase())).map(([k,v])=>[k,redactProviderData(v)]));if(typeof value==='string'&&/^https?:\/\//.test(value)){try{const u=new URL(value);for(const key of [...u.searchParams.keys()])if(['access_token','refresh_token','client_secret','appsecret_proof'].includes(key.toLowerCase()))u.searchParams.delete(key);return u.href;}catch{}}return value;}
export const credentialAAD=c=>`${c.owner_id}:${c.brand_id}:${c.platform}`;
export const credentials=c=>decrypt(c.credentials,credentialAAD(c));
export function wpPath(path){if(!/^wp\/v2\/(posts|pages|media|comments|categories|tags|users|settings|types|statuses|taxonomies|search|plugins|themes|templates|template-parts|blocks|menus|menu-items|navigation)(\/[a-zA-Z0-9_.-]+)*$/.test(path)||path.split('/').some(p=>p==='.'||p==='..'))throw new AppError('Niedozwolona ścieżka WordPress REST API.');return path;}
export function wpBase(raw){const u=publicUrl(raw);const allow=(process.env.WORDPRESS_ALLOWED_HOSTS||'').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);if(allow.length&&!allow.includes(u.hostname))throw new AppError('Domena nie jest dozwolona w konfiguracji.');return u.href.replace(/\/$/,'')+'/wp-json/';}
export async function provider(c,path,{method='GET',body,query={},binary,headers={}}={}){const secrets=credentials(c);let base,auth;if(c.platform==='wordpress'){wpPath(path);base=wpBase(c.base_url);auth={Authorization:'Basic '+Buffer.from(secrets.username+':'+secrets.password).toString('base64')};}else if(c.platform==='facebook'){base=`https://graph.facebook.com/${process.env.META_API_VERSION||'v25.0'}/`;auth={Authorization:'Bearer '+secrets.access_token};}else{base='https://api.linkedin.com/';auth={Authorization:'Bearer '+secrets.access_token,'LinkedIn-Version':process.env.LINKEDIN_API_VERSION||'202609','X-Restli-Protocol-Version':'2.0.0'};}
 const u=new URL(path,base);if(u.origin!==new URL(base).origin)throw new AppError('Nieprawidłowa ścieżka.');for(const[k,v]of Object.entries(query))if(v!==undefined)u.searchParams.set(k,String(v));const r=await safeFetch(u.href,{method,headers:{...auth,...(body?{'Content-Type':'application/json'}:{}),...headers},body:binary??(body?JSON.stringify(body):undefined)});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):{};}catch{data={};}if(!r.ok)throw new AppError(`Platforma odrzuciła żądanie (HTTP ${r.status}). Sprawdź uprawnienia, wersję API i dane.`,r.status>=500?502:400,r.status>=500?'uncertain':'provider_rejected');return {data:redactProviderData(data),id:r.headers.get('x-restli-id'),total:r.headers.get('x-wp-total')};}
export async function testConnection(c){if(c.platform==='wordpress'){const r=await provider(c,'wp/v2/users/me',{query:{context:'edit'}});return {name:r.data.name,id:String(r.data.id),capabilities:r.data.capabilities||{}};}if(c.platform==='facebook'){const r=await provider(c,encodeURIComponent(c.external_id),{query:{fields:'id,name'}});return {id:r.data.id,name:r.data.name};}if(c.external_id.startsWith('urn:li:organization:')){const r=await provider(c,'rest/organizations/'+c.external_id.split(':').pop());return {id:c.external_id,name:r.data.localizedName};}const r=await provider(c,'v2/userinfo');if(c.external_id!=='urn:li:person:'+r.data.sub)throw new AppError('URN osoby nie odpowiada tokenowi LinkedIn.');return{id:c.external_id,name:r.data.name};}
export async function publish(c,p){const v=p.payload||{};if(c.platform==='wordpress'){const type=v.type==='page'?'pages':'posts';const body={title:p.title,content:p.content,status:'publish'};for(const k of ['excerpt','slug','featured_media','categories','tags','meta'])if(v[k]!==undefined)body[k]=v[k];if(v.date_gmt)body.date_gmt=v.date_gmt.replace(/Z$/,'');const r=await provider(c,'wp/v2/'+type,{method:'POST',body});return {external_id:String(r.data.id),external_url:r.data.link};}
 if(c.platform==='facebook'){const page=encodeURIComponent(c.external_id);let r;if(v.video_url){publicUrl(v.video_url);r=await provider(c,page+'/videos',{method:'POST',body:{description:p.content,file_url:v.video_url}});}else if(v.image_urls?.length===1){publicUrl(v.image_urls[0]);r=await provider(c,page+'/photos',{method:'POST',body:{message:p.content,url:v.image_urls[0],published:true}});}else if(v.image_urls?.length){const images=[];for(const url of v.image_urls){publicUrl(url);const a=await provider(c,page+'/photos',{method:'POST',body:{url,published:false}});images.push({media_fbid:a.data.id});}r=await provider(c,page+'/feed',{method:'POST',body:{message:p.content,attached_media:images}});}else{if(v.link)publicUrl(v.link);r=await provider(c,page+'/feed',{method:'POST',body:{message:p.content,...(v.link?{link:v.link}:{})}});}const id=r.data.post_id||r.data.id;return {external_id:String(id),external_url:'https://www.facebook.com/'+id};}
 const body={author:c.external_id,commentary:p.content,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false};if(v.media_urn)body.content={media:{id:v.media_urn,...(v.alt_text?{altText:v.alt_text}:{})}};else if(v.link){publicUrl(v.link);body.content={article:{source:v.link,title:p.title||v.link,...(v.description?{description:v.description}:{})}};}const r=await provider(c,'rest/posts',{method:'POST',body});if(!r.id)throw new AppError('Brak identyfikatora publikacji. Sprawdź LinkedIn przed ponowieniem.',502,'uncertain');return{external_id:r.id,external_url:'https://www.linkedin.com/feed/update/'+encodeURIComponent(r.id)+'/'};}
export async function checkRemotePost(c,id){if(c.platform==='facebook'){if(!id.startsWith(c.external_id+'_')||!/^\d+_\d+$/.test(id))throw new AppError('Podaj identyfikator wpisu należącego do strony.');}else if(c.platform==='linkedin'){if(!/^urn:li:(share|ugcPost):\d+$/.test(id))throw new AppError('Nieprawidłowy URN wpisu.');const r=await provider(c,'rest/posts/'+encodeURIComponent(id));if(r.data.author!==c.external_id)throw new AppError('Wpis nie należy do tego konta.',403);}else if(!/^\d+$/.test(id))throw new AppError('Nieprawidłowy identyfikator wpisu.');}
export async function platformRead(c,{resource='posts',external_id,limit=25,page=1}){if(c.platform==='wordpress'){if(resource==='insights'){const r=await provider(c,'wp/v2/posts',{query:{per_page:1,status:'publish'}});return {published_posts:Number(r.total||0),note:'Liczba wpisów; statystyki odwiedzin wymagają osobnej integracji.'};}return(await provider(c,'wp/v2/'+(resource==='comments'?'comments':'posts'),{query:{per_page:limit,page,...(external_id?{post:external_id}:{})}})).data;}if(resource==='comments'){if(!external_id)throw new AppError('Podaj identyfikator wpisu.');await checkRemotePost(c,external_id);return(await provider(c,c.platform==='facebook'?encodeURIComponent(external_id)+'/comments':'rest/socialActions/'+encodeURIComponent(external_id)+'/comments',{query:{...(c.platform==='facebook'?{limit}:{count:limit,start:(page-1)*limit})}})).data;}
 if(c.platform==='facebook')return(await provider(c,encodeURIComponent(c.external_id)+(resource==='insights'?'/insights':'/feed'),{query:resource==='insights'?{metric:'page_post_engagements',period:'day'}:{fields:'id,message,created_time,permalink_url',limit}})).data;
 if(resource==='insights'){if(!c.external_id.startsWith('urn:li:organization:'))throw new AppError('Statystyki wymagają konta organizacji i produktu Community Management.');return(await provider(c,'rest/organizationalEntityShareStatistics',{query:{q:'organizationalEntity',organizationalEntity:c.external_id}})).data;}return(await provider(c,'rest/posts',{query:{q:'author',author:c.external_id,count:limit,start:(page-1)*limit,sortBy:'LAST_MODIFIED'}})).data;}
export async function comment(c,id,message){await checkRemotePost(c,id);if(c.platform==='wordpress')return(await provider(c,'wp/v2/comments',{method:'POST',body:{post:Number(id),content:message}})).data;if(c.platform==='facebook')return(await provider(c,encodeURIComponent(id)+'/comments',{method:'POST',body:{message}})).data;return(await provider(c,'rest/socialActions/'+encodeURIComponent(id)+'/comments',{method:'POST',body:{actor:c.external_id,message:{text:message}}})).data;}
export async function removeRemote(c,p){if(!p.external_id)throw new AppError('Brak identyfikatora opublikowanego wpisu.');if(c.platform==='wordpress')return(await provider(c,'wp/v2/'+(p.payload?.type==='page'?'pages':'posts')+'/'+p.external_id,{method:'DELETE',query:{force:false}})).data;await checkRemotePost(c,p.external_id);return(await provider(c,c.platform==='facebook'?encodeURIComponent(p.external_id):'rest/posts/'+encodeURIComponent(p.external_id),{method:'DELETE'})).data;}
export function linkedInUploadUrl(raw){const u=publicUrl(raw);if(u.hostname!=='www.linkedin.com'||!u.pathname.startsWith('/dms-uploads/'))throw new AppError('LinkedIn zwrócił nieoczekiwany adres wysyłania pliku.');return u.href;}
export async function uploadLinkedInImage(c,url){if(c.platform!=='linkedin')throw new AppError('Wybierz konto LinkedIn.');const image=await safeFetch(url);const mime=image.headers.get('content-type')?.split(';')[0];if(!image.ok||!['image/jpeg','image/png','image/gif'].includes(mime))throw new AppError('LinkedIn wymaga obrazu JPG, PNG lub GIF.');const init=await provider(c,'rest/images',{method:'POST',query:{action:'initializeUpload'},body:{initializeUploadRequest:{owner:c.external_id}}});const data=init.data.value;if(!/^urn:li:image:[a-zA-Z0-9_-]+$/.test(data?.image||''))throw new AppError('LinkedIn nie zwrócił identyfikatora obrazu.');const target=linkedInUploadUrl(data.uploadUrl);const result=await safeFetch(target,{method:'PUT',headers:{Authorization:'Bearer '+credentials(c).access_token,'Content-Type':mime},body:image.bytes});if(!result.ok)throw new AppError('LinkedIn odrzucił wysyłanie obrazu.');return{media_urn:data.image,status:'uploaded',note:'LinkedIn przetwarza obraz asynchronicznie. Użyj media_urn w payload szkicu po przetworzeniu.'};}
