import {context} from './auth.mjs';
import {db,rpc,owned} from './db.mjs';
import {AppError,origin,random,hash,decrypt,safeFetch} from './security.mjs';
import {saveConnection} from './actions.mjs';
async function app(ctx,platform){const rows=await db('provider_apps',{query:{owner_id:'eq.'+ctx.ownerId,platform:'eq.'+platform,limit:1}});if(!rows[0])throw new AppError('Najpierw zapisz aplikację OAuth w Ustawieniach.');return decrypt(rows[0].encrypted_config,ctx.ownerId+':'+platform);}
async function request(url,options){const r=await safeFetch(url,options);if(!r.ok)throw new AppError('Nie udało się połączyć przez OAuth. Sprawdź uprawnienia aplikacji i adres callback.');return r.json();}
export function providerAuthorizationUrl(platform,config,redirect,state){const target=new URL(platform==='facebook'?`https://www.facebook.com/${process.env.META_API_VERSION||'v25.0'}/dialog/oauth`:'https://www.linkedin.com/oauth/v2/authorization');const params={client_id:config.client_id,redirect_uri:redirect,response_type:'code',state};if(platform==='facebook'&&config.config_id)params.config_id=config.config_id;else params.scope=config.scopes.join(platform==='facebook'?',':' ');for(const[k,v]of Object.entries(params))target.searchParams.set(k,v);return target;}
export async function providerOAuth(req){const ctx=await context(req);if(ctx.actor!=='panel')throw new AppError('Otwórz panel właściciela.',403);const u=new URL(req.url);const match=u.pathname.match(/^\/api\/connect\/(facebook|linkedin)\/(start|callback)$/);if(!match)throw new AppError('Nieznana ścieżka.',404);const[,platform,step]=match;const config=await app(ctx,platform);const redirect=origin()+'/api/connect/'+platform+'/callback';
 if(step==='start'){const brand_id=u.searchParams.get('brand_id');if(!/^[0-9a-f-]{36}$/i.test(brand_id||''))throw new AppError('Wybierz markę.');await owned('brands',brand_id,ctx);const state=random();await db('oauth_states',{method:'POST',body:{state_hash:hash(state),owner_id:ctx.ownerId,brand_id,platform,expires_at:new Date(Date.now()+600000).toISOString()}});return Response.redirect(providerAuthorizationUrl(platform,config,redirect,state),302);}
 const rows=await rpc('consume_provider_state',{p_hash:hash(u.searchParams.get('state')||''),p_owner:ctx.ownerId,p_platform:platform});const state=rows[0];if(!state)throw new AppError('Sesja połączenia wygasła. Rozpocznij ponownie.');if(u.searchParams.has('error')||!u.searchParams.get('code'))throw new AppError('Nie udzielono dostępu do platformy.');const body=new URLSearchParams({grant_type:'authorization_code',code:u.searchParams.get('code'),client_id:config.client_id,client_secret:config.client_secret,redirect_uri:redirect}).toString();const token=await request(platform==='facebook'?`https://graph.facebook.com/${process.env.META_API_VERSION||'v25.0'}/oauth/access_token`:'https://www.linkedin.com/oauth/v2/accessToken',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!token.access_token)throw new AppError('Platforma nie zwróciła tokenu.');const auth={Authorization:'Bearer '+token.access_token};if(platform==='facebook'){const data=await request(`https://graph.facebook.com/${process.env.META_API_VERSION||'v25.0'}/me/accounts?fields=id,name,access_token&limit=100`,{headers:auth});if(!data.data?.length)throw new AppError('Brak stron dostępnych dla aplikacji. Nadaj dostęp w Meta.');for(const page of data.data)await saveConnection(ctx,{brand_id:state.brand_id,platform,name:page.name,external_id:page.id},{access_token:page.access_token});}else{const user=await request('https://api.linkedin.com/v2/userinfo',{headers:auth});await saveConnection(ctx,{brand_id:state.brand_id,platform,name:user.name||'LinkedIn',external_id:'urn:li:person:'+user.sub,expires_at:token.expires_in?new Date(Date.now()+token.expires_in*1000).toISOString():null},{access_token:token.access_token,...(token.refresh_token?{refresh_token:token.refresh_token}:{})});}return Response.redirect(origin()+'/?view=connections&notice=connected',302);}
