import {createCipheriv,createDecipheriv,randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import {lookup} from 'node:dns/promises';
import https from 'node:https';
import net from 'node:net';
export class AppError extends Error{constructor(message,status=400,code='invalid_request'){super(message);this.status=status;this.code=code;}}
export const hash=v=>createHash('sha256').update(v).digest('hex');
export const random=()=>randomBytes(32).toString('base64url');
export const challenge=v=>createHash('sha256').update(v).digest('base64url');
export const scopes=['read','draft','publish','engage','manage','admin'];
export function equal(a,b){return typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));}
function key(){const v=process.env.ENCRYPTION_KEY;if(!/^[a-f0-9]{64}$/i.test(v||''))throw new AppError('Ustaw klucz szyfrowania w Vercel.',503);return Buffer.from(v,'hex');}
export function encrypt(value,aad){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv);c.setAAD(Buffer.from(aad));const bytes=Buffer.concat([c.update(JSON.stringify(value)),c.final()]);return [iv,c.getAuthTag(),bytes].map(v=>v.toString('base64url')).join('.');}
export function decrypt(value,aad){const[iv,tag,bytes]=value.split('.').map(v=>Buffer.from(v,'base64url'));const c=createDecipheriv('aes-256-gcm',key(),iv);c.setAAD(Buffer.from(aad));c.setAuthTag(tag);return JSON.parse(Buffer.concat([c.update(bytes),c.final()]).toString());}
export function origin(){return new URL(process.env.APP_URL||'http://localhost:3000').origin;}
export function sameOrigin(req){if(req.headers.get('origin')!==origin())throw new AppError('Niedozwolone pochodzenie żądania.',403);}
export function assertScope(ctx,scope,brand){if(!ctx.scopes.includes(scope))throw new AppError('Brak uprawnienia: '+scope,403);if(brand&&ctx.brandIds!==null&&!ctx.brandIds.includes(brand))throw new AppError('Brak dostępu do tej marki.',403);}
export function publicUrl(raw){let u;try{u=new URL(raw);}catch{throw new AppError('Podaj pełny adres HTTPS.');}if(u.protocol!=='https:'||u.username||u.password||u.port&&u.port!=='443'||u.hash||net.isIP(u.hostname.replace(/^\[|\]$/g,''))||!u.hostname.includes('.')||/\.(local|internal|localhost|test|invalid)$/i.test(u.hostname))throw new AppError('Wymagany publiczny adres HTTPS bez danych logowania.');return u;}
export function publicIp(ip){if(!net.isIPv4(ip))return false;const[a,b,c]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&(b===168||b===0||b===88&&c===99)||a===100&&b>=64&&b<=127||a===198&&(b===18||b===19||b===51&&c===100)||a===203&&b===0&&c===113||a>=224);}
// Pin a validated DNS answer. HTTPS redirects are never followed with credentials.
export async function safeFetch(raw,{method='GET',headers={},body,maxBytes=8*1024*1024}={}){const u=publicUrl(raw),answers=await lookup(u.hostname,{all:true,family:4});if(!answers.length||answers.some(a=>!publicIp(a.address)))throw new AppError('Odrzucono prywatny adres sieci.');return new Promise((resolve,reject)=>{const req=https.request(u,{method,headers,timeout:20000,lookup:(_h,_o,cb)=>cb(null,answers[0].address,4)},res=>{let size=0;const chunks=[];res.on('data',chunk=>{size+=chunk.length;if(size>maxBytes){res.destroy();reject(new AppError('Przekroczono rozmiar transferu.',413));}else chunks.push(chunk);});res.on('end',()=>{const bytes=Buffer.concat(chunks);resolve({ok:res.statusCode>=200&&res.statusCode<300,status:res.statusCode,headers:new Headers(Object.entries(res.headers).filter(([,v])=>v!==undefined).map(([k,v])=>[k,Array.isArray(v)?v.join(','):v])),json:async()=>JSON.parse(bytes.toString()),text:async()=>bytes.toString(),bytes});});res.on('error',reject);});req.on('timeout',()=>req.destroy(new AppError('Przekroczono czas połączenia. Wynik zapisu wymaga sprawdzenia.',504,'uncertain')));req.on('error',reject);if(body)req.write(body);req.end();});}
export function cleanError(e){return e instanceof AppError?e.message:'Operacja nie powiodła się. Sprawdź konfigurację i połączenie.';}
export const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store',...headers}});
export async function bodyText(req,max=2*1024*1024){if(Number(req.headers.get('content-length')||0)>max)throw new AppError('Zbyt duże żądanie.',413);const reader=req.body?.getReader();if(!reader)return '';let size=0;const chunks=[];while(true){const{value,done}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new AppError('Zbyt duże żądanie.',413);}chunks.push(Buffer.from(value));}return Buffer.concat(chunks).toString();}
export async function bodyJson(req,max){try{return JSON.parse(await bodyText(req,max)||'{}');}catch(e){if(e instanceof AppError)throw e;throw new AppError('Nieprawidłowy JSON.');}}
